import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createLogger } from "../utils/logger";

const log = createLogger("PlatformUsageSeeder");

/** First-line sentinel identifying a PLATFORM_USAGE.md produced by this seeder.
 * When a file starts with this marker we consider it autogenerated and safe to
 * replace on the next startup. If the marker is missing we treat the file as
 * user-edited and leave it untouched so human-maintained notes aren't clobbered
 * on every deploy. */
export const PLATFORM_USAGE_MANAGED_MARKER = "<!-- nextclaw-managed: PLATFORM_USAGE v1 -->";

/** Outcome of `writePlatformUsageGuide` — useful for structured logging in the
 * calling Nitro plugin without it having to duplicate the decision tree. */
export type PlatformUsageWriteResult =
  | { status: "written"; target: string }
  | { status: "unchanged"; target: string }
  | { status: "user-edited-skipped"; target: string };

/** Writes (or refreshes) `<workspaceDir>/PLATFORM_USAGE.md` given the asset
 * content already loaded by the caller. Keeping I/O (read) in the Nitro plugin
 * and write-policy here lets us:
 *  - Use `useStorage("assets:usage")` in the plugin for Nitro-bundled output.
 *  - Fall back to `process.cwd()`-relative source files during `nuxi dev`.
 *  - Keep this module plain-node (no Nitro globals), so it stays trivially
 *    unit-testable and re-usable outside the server runtime.
 *
 * Rules:
 * - First run / file missing → write asset content with managed marker.
 * - File exists without marker → assumed user-edited, left alone.
 * - File exists with marker but content differs → overwritten.
 * - Asset content empty → logs a warning and skips write. */
export function writePlatformUsageGuide(
  workspaceDir: string,
  assetContent: string | null
): PlatformUsageWriteResult | null {
  if (!assetContent || assetContent.trim().length === 0) {
    log.warn("PLATFORM_USAGE.md asset is empty — skipping workspace seed");
    return null;
  }

  const managedContent = assetContent.startsWith(PLATFORM_USAGE_MANAGED_MARKER)
    ? assetContent
    : `${PLATFORM_USAGE_MANAGED_MARKER}\n${assetContent}`;
  const target = join(workspaceDir, "PLATFORM_USAGE.md");

  if (existsSync(target)) {
    try {
      const existing = readFileSync(target, "utf-8");
      if (!existing.startsWith(PLATFORM_USAGE_MANAGED_MARKER)) {
        log.info("PLATFORM_USAGE.md appears user-edited (no managed marker) — leaving as-is");
        return { status: "user-edited-skipped", target };
      }
      if (existing === managedContent) {
        return { status: "unchanged", target };
      }
    } catch {
      // Fall through to overwrite — an unreadable existing file is treated as
      // missing. The subsequent writeFileSync would surface any persistent
      // permissions issue to the caller.
    }
  }
  writeFileSync(target, managedContent, "utf-8");
  return { status: "written", target };
}
